import { z } from 'zod'
import { validatePrivateFileForUpload } from '../../../lib/security/filePolicy'
import { createPrivateDownloadUrl, createPrivateObjectPath } from '../../../lib/security/privateFiles'
import { getSupabaseClient } from '../../../lib/supabase/client'
import { trainingRecordInputSchema, type TrainingRecordInput } from '../schemas/training'

const uuid = z.string().uuid(); const numeric = z.coerce.number()
const rowSchema = z.object({ id: uuid, employee_id: uuid, employee_number: z.string(), employee_name: z.string(), topic: z.string(), provider: z.string().nullable(), completion_date: z.string(), duration_hours: numeric.nullable(), cost_ugx: numeric.nullable(), status: z.enum(['scheduled','attended','passed','failed']), expiry_date: z.string().nullable(), certificate_reference: z.string().nullable(), certificate_count: numeric.int(), created_at: z.string() })
const documentSchema = z.object({ id: uuid, storage_path: z.string(), original_file_name: z.string(), mime_type: z.string(), size_bytes: numeric, created_at: z.string() })
export type TrainingRecord = { id:string; employeeId:string; employeeNumber:string; employeeName:string; topic:string; provider:string|null; completionDate:string; durationHours:number|null; costUgx:number|null; status:'scheduled'|'attended'|'passed'|'failed'; expiryDate:string|null; certificateReference:string|null; certificateCount:number; createdAt:string }
export type TrainingDocument = { id:string; storagePath:string; originalFileName:string; mimeType:string; sizeBytes:number; createdAt:string }
interface Client { rpc(name:string, parameters?:Record<string,unknown>): PromiseLike<{data:unknown;error:unknown}> }
export interface TrainingApi { listForHr():Promise<TrainingRecord[]>; listMine():Promise<TrainingRecord[]>; save(input:TrainingRecordInput):Promise<string[]>; update(recordId:string,input:TrainingRecordInput):Promise<void>; listDocuments(recordId:string):Promise<TrainingDocument[]>; uploadDocuments(recordId:string,files:File[]):Promise<void>; removeDocument(documentId:string):Promise<void>; createDocumentDownload(path:string):Promise<string> }
const map = (row:z.infer<typeof rowSchema>):TrainingRecord => ({ id:row.id,employeeId:row.employee_id,employeeNumber:row.employee_number,employeeName:row.employee_name,topic:row.topic,provider:row.provider,completionDate:row.completion_date,durationHours:row.duration_hours,costUgx:row.cost_ugx,status:row.status,expiryDate:row.expiry_date,certificateReference:row.certificate_reference,certificateCount:row.certificate_count,createdAt:row.created_at })
export function createTrainingApi(client:Client=getSupabaseClient() as unknown as Client):TrainingApi { async function rpc(name:string,parameters?:Record<string,unknown>){const {data,error}=await client.rpc(name,parameters);if(error)throw new Error('Training request could not be completed.');return data} return {
  async listForHr(){await rpc('rpc_refresh_training_expiry_alerts');return z.array(rowSchema).parse(await rpc('rpc_list_training_records')).map(map)}, async listMine(){return z.array(rowSchema).parse(await rpc('rpc_list_my_training_records')).map(map)},
  async save(input){const value=trainingRecordInputSchema.parse(input);return z.array(uuid).parse(await rpc('rpc_log_training_records',{p_employee_ids:value.employeeIds,p_topic:value.topic,p_provider:value.provider||null,p_completion_date:value.completionDate,p_duration_hours:value.durationHours??null,p_cost_ugx:value.cost??null,p_status:value.status,p_expiry_date:value.expiryDate||null,p_certificate_reference:value.certificateReference||null}))},
  async update(recordId,input){const value=trainingRecordInputSchema.parse(input);await rpc('rpc_update_training_record',{p_record_id:uuid.parse(recordId),p_topic:value.topic,p_provider:value.provider||null,p_completion_date:value.completionDate,p_duration_hours:value.durationHours??null,p_cost_ugx:value.cost??null,p_status:value.status,p_expiry_date:value.expiryDate||null,p_certificate_reference:value.certificateReference||null})},
  async listDocuments(recordId){return z.array(documentSchema).parse(await rpc('rpc_list_training_documents',{p_training_record_id:uuid.parse(recordId)})).map(row=>({id:row.id,storagePath:row.storage_path,originalFileName:row.original_file_name,mimeType:row.mime_type,sizeBytes:row.size_bytes,createdAt:row.created_at}))},
  async uploadDocuments(recordId,files){if(!files.length||files.length>10)throw new Error('Attach between 1 and 10 certificates.');const supabase=getSupabaseClient();const auth=await supabase.auth.getUser();if(!auth.data.user)throw new Error('Sign in again before uploading certificates.');const uploaded:string[]=[];const attached:string[]=[];try{for(const file of files){const valid=await validatePrivateFileForUpload(file);if(!valid.ok)throw new Error('Use a PDF or phone-camera image no larger than 10 MB.');const path=createPrivateObjectPath({ownerId:auth.data.user.id,category:'training-certificates',recordId,extension:valid.extension});const stored=await supabase.storage.from('private-files').upload(path,file,{upsert:false,contentType:file.type});if(stored.error)throw stored.error;uploaded.push(path);attached.push(uuid.parse(await rpc('rpc_attach_training_document',{p_training_record_id:recordId,p_storage_path:path,p_original_file_name:file.name,p_mime_type:file.type.toLowerCase(),p_size_bytes:file.size})))}}catch(error){for(const documentId of attached)await rpc('rpc_remove_training_document',{p_document_id:documentId}).catch(()=>undefined);if(uploaded.length)await supabase.storage.from('private-files').remove(uploaded);throw error}},
  async removeDocument(documentId){await rpc('rpc_remove_training_document',{p_document_id:uuid.parse(documentId)})},
  async createDocumentDownload(path){const supabase=getSupabaseClient();return createPrivateDownloadUrl(path,{allowedOrigin:new URL(import.meta.env.VITE_SUPABASE_URL).origin,createSignedUrl:(objectPath,expiresIn)=>supabase.storage.from('private-files').createSignedUrl(objectPath,expiresIn)})}
} }
export const trainingApi=createTrainingApi()
