import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeft, CheckCircle2, Download, LockKeyhole, WalletCards } from 'lucide-react'
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Button } from '../../../components/ui/Button'
import { Modal } from '../../../components/ui/Modal'
import { StatusBadge } from '../../../components/ui/StatusBadge'
import { payrollApi, type PayrollApi } from '../api/payroll'
import { PayrollLineEditor } from '../components/PayrollLineEditor'
import { buildAmendmentDraftItems } from '../domain/amendmentDraft'
import { downloadMasterPayroll } from '../exports/masterPayroll'
import { bankPaymentCsv,downloadText,mtnBulkPayCsv,nssfCsv,payeCsv,whtCsv } from '../exports/paymentFiles'
import type { PayrollDraftItem, PayrollPayment, PayrollRun } from '../types'

const money=(value:number)=>new Intl.NumberFormat('en-UG',{style:'currency',currency:'UGX',maximumFractionDigits:0}).format(value)
export function PayrollRunPage({runId,api=payrollApi,permissions=[]}:{runId:string;api?:PayrollApi;permissions?:string[]}){
 const query=useQuery({queryKey:['payroll-run',runId],queryFn:()=>api.get(runId)})
 if(query.isLoading)return <section className="oh-workspace-page"><p role="status">Loading payroll run…</p></section>
 if(!query.data)return <section className="oh-workspace-page"><EmptyPayroll/></section>
 const revision=query.data.items.map((item)=>`${item.id}:${item.percentOfMonthWorked}:${item.overtimeHours}:${item.lineItems.length}`).join('|')
 return <PayrollRunContent key={`${query.data.status}:${revision}`} run={query.data} runId={runId} api={api} permissions={permissions}/>
}
function PayrollRunContent({run,runId,api,permissions}:{run:PayrollRun;runId:string;api:PayrollApi;permissions:string[]}){
 const employees=useQuery({queryKey:['payroll-employees'],queryFn:api.eligibleEmployees,enabled:permissions.includes('payroll.prepare')}),client=useQueryClient(),navigate=useNavigate(); const [draft,setDraft]=useState<PayrollDraftItem[]>(()=>run.items.map((i)=>({employeeId:i.employeeId,percentOfMonthWorked:i.percentOfMonthWorked,overtimeHours:i.overtimeHours,lineItems:i.lineItems}))),[dirty,setDirty]=useState(false),[reason,setReason]=useState(''),[approveOpen,setApproveOpen]=useState(false),[paymentOpen,setPaymentOpen]=useState(false),[amendOpen,setAmendOpen]=useState(false),[amendType,setAmendType]=useState<'supplemental'|'correction'>('supplemental'),[amendEmployees,setAmendEmployees]=useState<string[]>([]),[payment,setPayment]=useState<{paidOn:string;reference:string;method:PayrollPayment['method'];notes:string}>({paidOn:new Date().toISOString().slice(0,10),reference:'',method:'bank',notes:''})
 const refresh=async()=>{await Promise.all([client.invalidateQueries({queryKey:['payroll-run',runId]}),client.invalidateQueries({queryKey:['payroll-runs']})])}
 const save=useMutation({mutationFn:()=>api.replace(runId,draft,reason),onSuccess:async()=>{setDirty(false);await refresh()}}),approve=useMutation({mutationFn:()=>api.approve(runId,reason),onSuccess:async()=>{setApproveOpen(false);await refresh()}}),pay=useMutation({mutationFn:()=>api.recordPayment(runId,payment),onSuccess:async()=>{setPaymentOpen(false);await refresh()}}),amend=useMutation({mutationFn:()=>api.amend(runId,amendType,reason,buildAmendmentDraftItems(employees.data??[],amendEmployees,amendType)),onSuccess:async(id)=>{setAmendOpen(false);await refresh();navigate(`/hr/payroll/${id}`)}})
 const locked=run.status==='approved'
 const visibleItems=locked?run.items:run.items.filter((item)=>draft.some((entry)=>entry.employeeId===item.employeeId))
 const deferredCount=locked?0:run.items.length-visibleItems.length
 const exportCsv=async(kind:'bank'|'mtn'|'nssf'|'paye'|'wht')=>{await api.recordExport(run.id,null,kind);const factories={bank:bankPaymentCsv,mtn:mtnBulkPayCsv,nssf:nssfCsv,paye:payeCsv,wht:whtCsv};downloadText(factories[kind](run),`Egypro-${kind.toUpperCase()}-${run.periodStart.slice(0,7)}.csv`)}
 const exportPayslip=async(item:PayrollRun['items'][number])=>{await api.recordExport(run.id,item.id,'payslip');const {downloadPayslip}=await import('../exports/payslip');await downloadPayslip(run,item)}
 return <section className="oh-workspace-page"><Link className="oh-text-link" to="/hr/payroll"><ArrowLeft size={15}/>Back to payroll</Link><header className="oh-page-header payroll-run-header"><div><p>{run.runType} payroll · run {run.runNumber}</p><h1>{run.periodLabel}</h1><span>{locked?'Approved and locked — corrections require a linked new run.':'Draft — review every employee before HR approval.'}</span></div><StatusBadge tone={locked?'success':'warning'}>{run.status}</StatusBadge></header>
 <div className="payroll-summary">{[['Gross',run.totalGross],['Deductions',run.totalDeductions],['Net pay',run.totalNet],['Employees',run.items.length]].map(([label,value])=><article key={String(label)}><span>{label}</span><strong>{label==='Employees'?value:money(Number(value))}</strong></article>)}</div>
 <div className="payroll-actions">{!locked&&permissions.includes('payroll.prepare')&&<><input aria-label="Change reason" placeholder="Reason for draft changes" value={reason} onChange={(e)=>setReason(e.target.value)}/><Button variant="secondary" disabled={reason.trim().length<3||save.isPending||!draft.length||!dirty} onClick={()=>save.mutate()}>Save draft</Button></>}{!locked&&permissions.includes('payroll.approve')&&<Button disabled={dirty} onClick={()=>setApproveOpen(true)}><CheckCircle2 size={17}/>Approve payroll</Button>}{locked&&permissions.includes('payroll.prepare')&&<Button variant="secondary" onClick={()=>{setReason('');setAmendEmployees([]);setAmendOpen(true)}}>Create supplemental / correction</Button>}{locked&&permissions.includes('payroll.export')&&<div className="payroll-export-grid"><Button variant="secondary" onClick={()=>void api.recordExport(run.id,null,'master').then(()=>downloadMasterPayroll(run))}><Download size={16}/>Master Excel</Button>{(['bank','mtn','nssf','paye','wht'] as const).map((kind)=><Button key={kind} variant="secondary" onClick={()=>void exportCsv(kind)}>{kind.toUpperCase()} CSV</Button>)}</div>}{locked&&permissions.includes('payroll.record_payment')&&!run.payment&&<Button onClick={()=>setPaymentOpen(true)}><WalletCards size={17}/>Record payment</Button>}</div>
 {dirty&&<p role="status">Save changes before approval.</p>}
 {deferredCount>0&&<p role="status">{deferredCount} employee{deferredCount===1?'':'s'} deferred from this run.</p>}
 {run.payment&&<div className="payroll-payment"><CheckCircle2/><div><strong>Payment recorded</strong><span>{run.payment.paidOn} · {run.payment.reference} · {money(run.payment.amount)}</span></div></div>}
 <div className="payroll-items">{visibleItems.map((item)=>{const value=draft.find((d)=>d.employeeId===item.employeeId)??{employeeId:item.employeeId,percentOfMonthWorked:item.percentOfMonthWorked,overtimeHours:item.overtimeHours,lineItems:item.lineItems};return <article key={item.id} className="payroll-item-card"><PayrollLineEditor employeeName={item.employeeName} value={value} locked={locked} onChange={(next)=>{setDraft((current)=>current.map((d)=>d.employeeId===next.employeeId?next:d));setDirty(true)}} onDefer={()=>{setDraft((current)=>current.filter((d)=>d.employeeId!==item.employeeId));setDirty(true)}}/><div className="payroll-item-values"><span>Gross <strong>{money(item.taxableGross)}</strong></span><span>Deductions <strong>{money(item.totalDeductions)}</strong></span><span>Net <strong>{money(item.netPay)}</strong></span>{locked&&permissions.includes('payroll.export')&&<button className="oh-text-link" onClick={()=>void exportPayslip(item)}>Payslip PDF</button>}</div></article>})}</div>
 <Modal open={approveOpen} title="Approve and lock payroll" onClose={()=>setApproveOpen(false)}><form className="oh-form-stack" onSubmit={(e)=>{e.preventDefault();approve.mutate()}}><p><LockKeyhole size={18}/>Approval is permanent. Later changes use a supplemental or correction run.</p><label>Approval reason<textarea aria-label="Approval reason" value={reason} onChange={(e)=>setReason(e.target.value)} required minLength={3}/></label><Button type="submit" disabled={reason.trim().length<3||approve.isPending}>Approve and lock</Button></form></Modal>
 <Modal open={paymentOpen} title="Record CFO payment" onClose={()=>setPaymentOpen(false)}><form className="oh-form-stack" onSubmit={(e)=>{e.preventDefault();pay.mutate()}}><label>Payment date<input type="date" value={payment.paidOn} max={new Date().toISOString().slice(0,10)} onChange={(e)=>setPayment((current)=>({...current,paidOn:e.target.value}))}/></label><label>Payment reference<input aria-label="Payment reference" value={payment.reference} onChange={(e)=>setPayment((current)=>({...current,reference:e.target.value}))} required minLength={3}/></label><label>Method<select value={payment.method} onChange={(e)=>setPayment((current)=>({...current,method:e.target.value as PayrollPayment['method']}))}><option value="bank">Bank</option><option value="mobile_money">Mobile money</option><option value="cash">Cash</option><option value="other">Other</option></select></label><label>Notes<textarea value={payment.notes} onChange={(e)=>setPayment((current)=>({...current,notes:e.target.value}))}/></label><Button type="submit" disabled={payment.reference.trim().length<3||pay.isPending}>Confirm payment</Button></form></Modal>
 <Modal open={amendOpen} title="Create linked payroll run" onClose={()=>setAmendOpen(false)}><form className="oh-form-stack" onSubmit={(e)=>{e.preventDefault();amend.mutate()}}><label>Run type<select value={amendType} onChange={(e)=>setAmendType(e.target.value as 'supplemental'|'correction')}><option value="supplemental">Supplemental / deferred payment</option><option value="correction">Correction</option></select></label><p>{amendType==='correction'?'Correction runs start at zero pay. Add only the correction earnings or deductions required.':'Supplemental runs restore the selected employee’s normal period percentage.'}</p><label>Reason<textarea value={reason} onChange={(e)=>setReason(e.target.value)} required minLength={3}/></label><fieldset><legend>Employees to include</legend><div className="payroll-employee-picker">{(employees.data??[]).map((employee)=><label key={employee.id}><input type="checkbox" checked={amendEmployees.includes(employee.id)} onChange={(e)=>setAmendEmployees((current)=>e.target.checked?[...current,employee.id]:current.filter((id)=>id!==employee.id))}/><span>{employee.employeeName}<small>{employee.employeeNumber}</small></span></label>)}</div></fieldset><Button type="submit" disabled={!amendEmployees.length||reason.trim().length<3||amend.isPending}>Create linked draft</Button></form></Modal>
 </section>
}
function EmptyPayroll(){return <div><h1>Payroll run not found</h1><p>Return to the payroll list and try again.</p></div>}
