import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { BarChart3, Download, Plus, Upload } from 'lucide-react'
import { useMemo, useRef, useState } from 'react'
import { useSearchParams } from 'react-router-dom'

import { Button } from '../../../components/ui/Button'
import { FormError } from '../../../components/ui/FormError'
import { Modal } from '../../../components/ui/Modal'
import { employeeApi, type EmployeeApi } from '../api/employees'
import { performanceApi, type PerformanceApi, type PerformanceReview } from '../api/performance'

const statusLabel: Record<PerformanceReview['status'], string> = { draft: 'Manager draft', reopened: 'Changes requested', manager_submitted: 'Awaiting HR', hr_approved: 'Released', employee_acknowledged: 'Acknowledged' }

export function PerformanceManagementPage({ api = performanceApi, employeesApi = employeeApi }: { api?: PerformanceApi; employeesApi?: EmployeeApi }) {
  const queryClient = useQueryClient(); const [params, setParams] = useSearchParams(); const fileRef = useRef<HTMLInputElement>(null)
  const [creating, setCreating] = useState(false); const [assigning, setAssigning] = useState(false); const [cycleForm, setCycleForm] = useState({ name: '', startDate: '', endDate: '' }); const [assignment, setAssignment] = useState({ employeeId: '', reviewerProfileId: '' }); const [decisionNote, setDecisionNote] = useState(''); const [selected, setSelected] = useState<PerformanceReview | null>(null)
  const [importing, setImporting] = useState(false); const [importMessage, setImportMessage] = useState('')
  const cycles = useQuery({ queryKey: ['performance-cycles'], queryFn: api.listCycles }); const employees = useQuery({ queryKey: ['employees', 'performance'], queryFn: employeesApi.list }); const reviewers = useQuery({ queryKey: ['performance-reviewers'], queryFn: api.listReviewers })
  const activeCycle = cycles.data?.find((cycle) => cycle.status === 'active') ?? cycles.data?.[0]
  const reviews = useQuery({ queryKey: ['performance-reviews', activeCycle?.id], queryFn: () => api.listReviews(activeCycle?.id), enabled: Boolean(activeCycle) })
  const refresh = async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ['performance-cycles'] }), queryClient.invalidateQueries({ queryKey: ['performance-reviews'] })]) }
  const create = useMutation({ mutationFn: api.createCycle, onSuccess: async () => { setCreating(false); setCycleForm({ name: '', startDate: '', endDate: '' }); await refresh() } }); const setStatus = useMutation({ mutationFn: ({ id, status }: { id: string; status: 'draft'|'active'|'closed' }) => api.setCycleStatus(id, status), onSuccess: refresh }); const start = useMutation({ mutationFn: () => { if (!activeCycle) throw new Error('Create or activate a cycle first.'); return api.startReview({ ...assignment, cycleId: activeCycle.id }) }, onSuccess: async () => { setAssigning(false); setAssignment({ employeeId: '', reviewerProfileId: '' }); await refresh() } }); const decide = useMutation({ mutationFn: ({ reviewId, decision }: { reviewId: string; decision: 'approved'|'reopened' }) => api.decide({ reviewId, decision, reason: decisionNote }), onSuccess: async () => { setSelected(null); setDecisionNote(''); await refresh() } })
  const viewing = selected ?? reviews.data?.find((review) => review.id === params.get('review')) ?? null
  const closeReview = () => { setSelected(null); if (params.has('review')) { const next = new URLSearchParams(params); next.delete('review'); setParams(next, { replace: true }) } }
  const assignedEmployees = useMemo(() => new Set((reviews.data ?? []).map((review) => review.employeeId)), [reviews.data])
  async function exportWorkbook() { const XLSX = await import('@e965/xlsx'); const rows = (employees.data ?? []).filter((employee) => employee.active).map((employee) => ({ 'Employee Number': employee.employeeNumber, 'Employee Name': employee.legalName, 'Reviewer Name': '', 'Goal 1': '', 'Rating 1 (1-5)': '', 'Goal 2': '', 'Rating 2 (1-5)': '', 'Goal 3': '', 'Rating 3 (1-5)': '', 'Manager Comments': '', 'Recommend Increment (Yes/No)': 'No', 'Recommend Promotion (Yes/No)': 'No' })); const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, XLSX.utils.json_to_sheet(rows), 'Performance Reviews'); XLSX.writeFile(book, `OneHub_Performance_${activeCycle?.name.replace(/\s+/g, '_') ?? 'Template'}.xlsx`, { compression: true }) }
  async function importWorkbook(file: File) {
    if (!activeCycle || activeCycle.status !== 'active') { setImportMessage('Activate a performance cycle before importing reviews.'); return }
    setImporting(true); setImportMessage('')
    try {
      const XLSX = await import('@e965/xlsx'); const workbook = XLSX.read(await file.arrayBuffer(), { type: 'array' }); const sheet = workbook.Sheets[workbook.SheetNames[0]]; const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(sheet, { defval: '' }); let imported = 0; const problems: string[] = []
      for (const [index, row] of rows.entries()) {
        const employeeKey = String(row['Employee Number'] || row['Employee Name']).trim().toLowerCase(); const reviewerKey = String(row['Reviewer Name'] || row['Reviewer Email/Name']).trim().toLowerCase(); const employee = (employees.data ?? []).find((item) => item.employeeNumber.toLowerCase() === employeeKey || item.legalName.toLowerCase() === employeeKey); const reviewer = (reviewers.data ?? []).find((item) => item.displayName.toLowerCase() === reviewerKey)
        const goals = [1,2,3].map((number) => ({ description: String(row[`Goal ${number}`]).trim(), managerRating: Number(row[`Rating ${number} (1-5)`]) })).filter((goal) => goal.description)
        if (!employee || !reviewer || !goals.length || !String(row['Manager Comments']).trim()) { problems.push(`Row ${index + 2}: employee, reviewer, goals or comments could not be matched.`); continue }
        await api.importReview({ employeeId: employee.id, cycleId: activeCycle.id, reviewerProfileId: reviewer.profileId, managerComments: String(row['Manager Comments']), recommendIncrement: /^yes$/i.test(String(row['Recommend Increment (Yes/No)'])), recommendPromotion: /^yes$/i.test(String(row['Recommend Promotion (Yes/No)'])), goals }); imported += 1
      }
      setImportMessage(`${imported} review${imported === 1 ? '' : 's'} imported.${problems.length ? ` ${problems.length} row${problems.length === 1 ? '' : 's'} need correction: ${problems.slice(0, 3).join(' ')}` : ''}`); await refresh()
    } catch (error) { setImportMessage(error instanceof Error ? error.message : 'The workbook could not be imported.') } finally { setImporting(false); if (fileRef.current) fileRef.current.value = '' }
  }
  return <section className="oh-workspace-page">
    <header className="oh-page-header"><div><p>People development</p><h1>Performance Management</h1><span>Run review cycles, assign managers, calibrate assessments and release outcomes.</span></div><div className="oh-inline-actions"><Button variant="secondary" onClick={() => exportWorkbook()}><Download size={18} /> Excel template</Button><input ref={fileRef} hidden type="file" accept=".xlsx,.xls" onChange={(event) => { const file = event.target.files?.[0]; if (file) void importWorkbook(file) }} /><Button variant="secondary" loading={importing} onClick={() => fileRef.current?.click()}><Upload size={18} /> Import reviews</Button><Button onClick={() => setCreating(true)}><Plus size={18} /> New review cycle</Button></div></header>
    {importMessage ? <div className="oh-card" role="status">{importMessage}</div> : null}
    {(cycles.isLoading || employees.isLoading || reviewers.isLoading) ? <p role="status">Loading performance workspace…</p> : null}{(cycles.isError || employees.isError || reviewers.isError) ? <FormError>Performance management could not be loaded.</FormError> : null}
    <div className="oh-kpi-band"><article className="oh-kpi"><span className="oh-kpi__label">Review cycles</span><strong className="oh-kpi__value">{cycles.data?.length ?? 0}</strong></article><article className="oh-kpi"><span className="oh-kpi__label">Assigned reviews</span><strong className="oh-kpi__value">{activeCycle?.totalReviews ?? 0}</strong></article><article className="oh-kpi"><span className="oh-kpi__label">Completed</span><strong className="oh-kpi__value">{activeCycle?.completedReviews ?? 0}</strong></article><article className="oh-kpi"><span className="oh-kpi__label">Awaiting HR</span><strong className="oh-kpi__value oh-kpi__value--warning">{reviews.data?.filter((review) => review.status === 'manager_submitted').length ?? 0}</strong></article></div>
    <section className="oh-card"><div className="oh-page-header"><div><p>Current cycle</p><h2>{activeCycle?.name ?? 'No cycle configured'}</h2><span>{activeCycle ? `${activeCycle.startDate} to ${activeCycle.endDate}` : 'Create a review cycle to begin.'}</span></div>{activeCycle ? <div className="oh-inline-actions">{activeCycle.status !== 'active' ? <Button variant="secondary" onClick={() => setStatus.mutate({ id: activeCycle.id, status: 'active' })}>Activate cycle</Button> : <Button variant="secondary" onClick={() => setStatus.mutate({ id: activeCycle.id, status: 'closed' })}>Close cycle</Button>}<Button onClick={() => setAssigning(true)}><Plus size={17} /> Assign review</Button></div> : null}</div></section>
    <section className="oh-card oh-leave-requests"><h2>Review roster</h2>{reviews.data?.length ? <div className="oh-table-wrap"><table className="oh-table"><thead><tr><th>Employee</th><th>Reviewer</th><th>Score</th><th>Status</th><th>Action</th></tr></thead><tbody>{reviews.data.map((review) => <tr key={review.id}><td>{review.employeeName}<small>{review.employeeNumber}</small></td><td>{review.reviewerName}</td><td>{review.overallScore?.toFixed(1) ?? '—'}</td><td>{statusLabel[review.status]}</td><td><Button className="oh-button--small" variant="secondary" onClick={() => setSelected(review)}>{review.status === 'manager_submitted' ? 'Review assessment' : 'View review'}</Button></td></tr>)}</tbody></table></div> : <p>No employees have been assigned to this cycle.</p>}</section>
    <Modal open={creating} title="Create performance cycle" onClose={() => setCreating(false)}><form className="oh-form" onSubmit={(event) => { event.preventDefault(); create.mutate(cycleForm) }}><label className="oh-field"><span className="oh-field__label">Cycle name</span><input className="oh-input" value={cycleForm.name} onChange={(event) => setCycleForm({ ...cycleForm, name: event.target.value })} /></label><div className="oh-form-grid"><label className="oh-field"><span className="oh-field__label">Start date</span><input className="oh-input" type="date" value={cycleForm.startDate} onChange={(event) => setCycleForm({ ...cycleForm, startDate: event.target.value })} /></label><label className="oh-field"><span className="oh-field__label">End date</span><input className="oh-input" type="date" value={cycleForm.endDate} onChange={(event) => setCycleForm({ ...cycleForm, endDate: event.target.value })} /></label></div>{create.isError ? <FormError>{create.error.message}</FormError> : null}<div className="oh-form-actions"><Button variant="secondary" onClick={() => setCreating(false)}>Cancel</Button><Button type="submit" loading={create.isPending}>Create cycle</Button></div></form></Modal>
    <Modal open={assigning} title="Assign employee review" onClose={() => setAssigning(false)}><div className="oh-form"><label className="oh-field"><span className="oh-field__label">Employee</span><select className="oh-input" value={assignment.employeeId} onChange={(event) => setAssignment({ ...assignment, employeeId: event.target.value })}><option value="">Select employee…</option>{(employees.data ?? []).filter((employee) => employee.active && !assignedEmployees.has(employee.id)).map((employee) => <option key={employee.id} value={employee.id}>{employee.legalName} · {employee.employeeNumber}</option>)}</select></label><label className="oh-field"><span className="oh-field__label">Assigned reviewer</span><select className="oh-input" value={assignment.reviewerProfileId} onChange={(event) => setAssignment({ ...assignment, reviewerProfileId: event.target.value })}><option value="">Select manager…</option>{reviewers.data?.map((reviewer) => <option key={reviewer.profileId} value={reviewer.profileId}>{reviewer.displayName} · {reviewer.roleLabel}</option>)}</select></label>{start.isError ? <FormError>{start.error.message}</FormError> : null}<div className="oh-form-actions"><Button variant="secondary" onClick={() => setAssigning(false)}>Cancel</Button><Button disabled={!assignment.employeeId || !assignment.reviewerProfileId} loading={start.isPending} onClick={() => start.mutate()}>Assign review</Button></div></div></Modal>
    <Modal open={Boolean(viewing)} title="Performance review" onClose={closeReview}>{viewing ? <div className="oh-form"><div className="oh-card"><BarChart3 size={20} /><h3>{viewing.employeeName}</h3><p>{viewing.cycleName} · Reviewer: {viewing.reviewerName}</p><strong>{statusLabel[viewing.status]}</strong>{viewing.goals.map((goal) => <p key={goal.id}>{goal.description}: <strong>{goal.managerRating}/5</strong></p>)}<p>{viewing.managerComments}</p></div>{viewing.status === 'manager_submitted' ? <><label className="oh-field"><span className="oh-field__label">HR decision note</span><textarea className="oh-input oh-textarea" value={decisionNote} onChange={(event) => setDecisionNote(event.target.value)} /></label><div className="oh-form-actions"><Button variant="secondary" disabled={decisionNote.trim().length < 3} onClick={() => decide.mutate({ reviewId: viewing.id, decision: 'reopened' })}>Request changes</Button><Button disabled={decisionNote.trim().length < 3} onClick={() => decide.mutate({ reviewId: viewing.id, decision: 'approved' })}>Approve review</Button></div></> : null}{decide.isError ? <FormError>{decide.error.message}</FormError> : null}</div> : null}</Modal>
  </section>
}
