import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { WalletCards } from 'lucide-react'
import { useState } from 'react'
import { useSearchParams } from 'react-router-dom'

import { Button } from '../../../components/ui/Button'
import { FormError } from '../../../components/ui/FormError'
import { Modal } from '../../../components/ui/Modal'
import { employeeApi, type EmployeeApi } from '../api/employees'
import { staffAdvancesApi, type StaffAdvance, type StaffAdvancesApi } from '../api/staffAdvances'
import { StaffAdvanceDetails, StaffAdvanceStatus } from '../components/StaffAdvanceDetails'
import { StaffAdvanceForm } from '../components/StaffAdvanceForm'

const currency = new Intl.NumberFormat('en-UG', { style: 'currency', currency: 'UGX', maximumFractionDigits: 0 })
const transitionLabels = { flagged: 'Flag', reopened: 'Reactivate', settled: 'Settle', written_off: 'Write off', voided: 'Void' } as const

export function StaffAdvancesPage({ api = staffAdvancesApi, employeesApi = employeeApi }: { api?: StaffAdvancesApi; employeesApi?: EmployeeApi }) {
  const [logging, setLogging] = useState(false); const [selected, setSelected] = useState<StaffAdvance | null>(null); const [rejecting, setRejecting] = useState<StaffAdvance | null>(null); const [reason, setReason] = useState(''); const [repaying, setRepaying] = useState<StaffAdvance | null>(null); const [adjusting, setAdjusting] = useState<{ advance: StaffAdvance; transition: 'flagged' | 'reopened' | 'settled' | 'written_off' | 'voided' } | null>(null); const [repayment, setRepayment] = useState({ amount: '', payrollPeriod: new Date().toISOString().slice(0, 7) + '-01', source: 'manual' as 'manual'|'payroll'|'exit', notes: '' }); const [params, setParams] = useSearchParams(); const queryClient = useQueryClient()
  const advances = useQuery({ queryKey: ['hr-staff-advances'], queryFn: api.listForHr }); const employees = useQuery({ queryKey: ['employees', 'staff-advance-options'], queryFn: employeesApi.list }); const refresh = () => queryClient.invalidateQueries({ queryKey: ['hr-staff-advances'] })
  const log = useMutation({ mutationFn: (input: Parameters<StaffAdvancesApi['logForEmployee']>[0]) => api.logForEmployee(input), onSuccess: async () => { setLogging(false); await refresh() } })
  const decide = useMutation({ mutationFn: (input: Parameters<StaffAdvancesApi['decide']>[0]) => api.decide(input), onSuccess: refresh })
  const transition = useMutation({ mutationFn: (input: Parameters<StaffAdvancesApi['transition']>[0]) => api.transition(input), onSuccess: async () => { setAdjusting(null); setReason(''); await refresh() } })
  const repay = useMutation({ mutationFn: () => { if (!repaying) throw new Error('Select a staff advance.'); return api.recordRepayment({ advanceId: repaying.id, amount: Number(repayment.amount), payrollPeriod: repayment.payrollPeriod, source: repayment.source, notes: repayment.notes }) }, onSuccess: async () => { setRepaying(null); setRepayment({ ...repayment, amount: '', notes: '' }); await refresh() } })
  const pending = (advances.data ?? []).filter((advance) => advance.status === 'pending'); const active = (advances.data ?? []).filter((advance) => ['active', 'flagged'].includes(advance.status)); const outstanding = active.reduce((sum, advance) => sum + advance.balanceRemaining, 0); const viewing = selected ?? advances.data?.find((advance) => advance.id === params.get('advance')) ?? null
  const close = () => { setSelected(null); if (params.has('advance')) { const next = new URLSearchParams(params); next.delete('advance'); setParams(next, { replace: true }) } }
  return <section>
    <header className="oh-page-header"><div><p>People finance</p><h1>Staff Advances</h1><span>Log walk-in advances, review employee requests and track payroll recovery.</span></div><Button onClick={() => setLogging(true)}><WalletCards size={18} /> Log advance</Button></header>
    {(advances.isLoading || employees.isLoading) ? <p role="status">Loading staff advances…</p> : null}{(advances.isError || employees.isError) ? <FormError>Staff advances could not be loaded.</FormError> : null}
    <div className="oh-kpi-band"><article className="oh-kpi"><span className="oh-kpi__label">Pending HR review</span><strong className="oh-kpi__value oh-kpi__value--warning">{pending.length}</strong></article><article className="oh-kpi"><span className="oh-kpi__label">Active advances</span><strong className="oh-kpi__value">{active.length}</strong></article><article className="oh-kpi"><span className="oh-kpi__label">Outstanding balance</span><strong className="oh-kpi__value">{currency.format(outstanding)}</strong></article></div>
    {pending.length ? <section className="oh-card oh-leave-requests"><h2>Pending requests</h2><div className="oh-table-wrap"><table className="oh-table"><thead><tr><th>Employee</th><th>Reason</th><th>Amount</th><th>Instalments</th><th>Actions</th></tr></thead><tbody>{pending.map((advance) => <tr key={advance.id}><td>{advance.employeeName}<small>{advance.employeeNumber}</small></td><td>{advance.reason}</td><td>{currency.format(advance.amount)}</td><td>{advance.instalments} × {currency.format(advance.monthlyDeduction)}</td><td><div className="oh-inline-actions"><Button className="oh-button--small" variant="secondary" onClick={() => setSelected(advance)}>Details</Button><Button className="oh-button--small" loading={decide.isPending} onClick={() => decide.mutate({ advanceId: advance.id, decision: 'approved', reason: 'Approved by HR' })}>Approve</Button><Button className="oh-button--small" variant="secondary" onClick={() => setRejecting(advance)}>Reject</Button></div></td></tr>)}</tbody></table></div></section> : null}
    <section className="oh-card oh-leave-requests"><h2>All advances</h2>{advances.data?.length ? <div className="oh-table-wrap"><table className="oh-table"><thead><tr><th>Employee</th><th>Date</th><th>Amount</th><th>Balance</th><th>Status</th><th>Action</th></tr></thead><tbody>{advances.data.map((advance) => <tr key={advance.id}><td>{advance.employeeName}</td><td>{advance.dateIssued}</td><td>{currency.format(advance.amount)}</td><td>{currency.format(advance.balanceRemaining)}</td><td><StaffAdvanceStatus status={advance.status} /></td><td><div className="oh-inline-actions"><Button className="oh-button--small" variant="secondary" onClick={() => setSelected(advance)}>View details</Button>{['active', 'flagged'].includes(advance.status) ? <Button className="oh-button--small" variant="secondary" onClick={() => setRepaying(advance)}>Record repayment</Button> : null}{advance.status === 'active' ? <Button className="oh-button--small" variant="secondary" onClick={() => setAdjusting({ advance, transition: 'flagged' })}>Flag advance</Button> : null}{advance.status === 'flagged' ? <Button className="oh-button--small" variant="secondary" onClick={() => setAdjusting({ advance, transition: 'reopened' })}>Reactivate</Button> : null}{['active', 'flagged'].includes(advance.status) ? <><Button className="oh-button--small" variant="secondary" onClick={() => setAdjusting({ advance, transition: 'settled' })}>Settle</Button><Button className="oh-button--small" variant="secondary" onClick={() => setAdjusting({ advance, transition: 'written_off' })}>Write off</Button></> : null}{advance.status === 'rejected' ? <Button className="oh-button--small" variant="secondary" onClick={() => setAdjusting({ advance, transition: 'voided' })}>Void</Button> : null}</div></td></tr>)}</tbody></table></div> : <p>No staff advances recorded.</p>}</section>
    <Modal open={logging} title="Log staff advance" onClose={() => setLogging(false)}><StaffAdvanceForm employeeOptions={(employees.data ?? []).filter((employee) => employee.active).map((employee) => ({ id: employee.id, name: `${employee.legalName} · ${employee.employeeNumber}` }))} submitting={log.isPending} onCancel={() => setLogging(false)} onSubmit={(value) => log.mutateAsync(value as Parameters<StaffAdvancesApi['logForEmployee']>[0])} />{log.isError ? <FormError>{log.error.message}</FormError> : null}</Modal>
    <Modal open={Boolean(viewing)} title="Staff advance details" onClose={close}>{viewing ? <StaffAdvanceDetails advance={viewing} api={api} /> : null}</Modal>
    <Modal open={Boolean(rejecting)} title="Reject staff advance" onClose={() => setRejecting(null)}><label className="oh-field"><span className="oh-field__label">Reason for rejection</span><textarea className="oh-input oh-textarea" value={reason} onChange={(event) => setReason(event.target.value)} /></label><div className="oh-form-actions"><Button variant="secondary" onClick={() => setRejecting(null)}>Cancel</Button><Button variant="danger" disabled={reason.trim().length < 3} loading={decide.isPending} onClick={() => rejecting && decide.mutate({ advanceId: rejecting.id, decision: 'rejected', reason }, { onSuccess: () => { setRejecting(null); setReason('') } })}>Reject request</Button></div></Modal>
    <Modal open={Boolean(repaying)} title="Record staff advance repayment" onClose={() => setRepaying(null)}><div className="oh-form"><label className="oh-field"><span className="oh-field__label">Payroll period</span><input className="oh-input" type="date" value={repayment.payrollPeriod} onChange={(event) => setRepayment({ ...repayment, payrollPeriod: event.target.value })} /></label><label className="oh-field"><span className="oh-field__label">Amount (UGX)</span><input className="oh-input" type="number" min="1" value={repayment.amount} onChange={(event) => setRepayment({ ...repayment, amount: event.target.value })} /></label><label className="oh-field"><span className="oh-field__label">Source</span><select className="oh-input" value={repayment.source} onChange={(event) => setRepayment({ ...repayment, source: event.target.value as typeof repayment.source })}><option value="manual">Manual payment</option><option value="payroll">Payroll deduction</option><option value="exit">Exit recovery</option></select></label><label className="oh-field"><span className="oh-field__label">Notes</span><textarea className="oh-input oh-textarea" value={repayment.notes} onChange={(event) => setRepayment({ ...repayment, notes: event.target.value })} /></label><div className="oh-form-actions"><Button variant="secondary" onClick={() => setRepaying(null)}>Cancel</Button><Button loading={repay.isPending} onClick={() => repay.mutate()}>Record repayment</Button></div>{repay.isError ? <FormError>{repay.error.message}</FormError> : null}</div></Modal>
    <Modal open={Boolean(adjusting)} title={`${adjusting ? transitionLabels[adjusting.transition] : ''} staff advance`} onClose={() => setAdjusting(null)}><label className="oh-field"><span className="oh-field__label">Reason</span><textarea className="oh-input oh-textarea" value={reason} onChange={(event) => setReason(event.target.value)} /></label><div className="oh-form-actions"><Button variant="secondary" onClick={() => setAdjusting(null)}>Cancel</Button><Button disabled={reason.trim().length < 3} loading={transition.isPending} onClick={() => adjusting && transition.mutate({ advanceId: adjusting.advance.id, transition: adjusting.transition, reason })}>{adjusting ? `${transitionLabels[adjusting.transition]}${adjusting.transition === 'flagged' ? ' advance' : ''}` : ''}</Button></div>{transition.isError ? <FormError>{transition.error.message}</FormError> : null}</Modal>
  </section>
}
