import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query'
import { AlertTriangle,BookOpen,Clock,Plus,Search } from 'lucide-react'
import { useMemo,useState } from 'react'
import { Button } from '../../../components/ui/Button'
import { FormError } from '../../../components/ui/FormError'
import { Modal } from '../../../components/ui/Modal'
import { employeeApi,type EmployeeApi } from '../api/employees'
import { trainingApi,type TrainingApi,type TrainingRecord } from '../api/training'
import { TrainingDocumentsModal } from '../components/TrainingDocumentsModal'
import type { TrainingRecordInput } from '../schemas/training'

const today=()=>new Date().toISOString().slice(0,10)
const empty=():TrainingRecordInput=>({employeeIds:[],topic:'',provider:'',completionDate:today(),durationHours:null,cost:null,status:'passed',expiryDate:null,certificateReference:''})
export function TrainingManagementPage({api=trainingApi,employeesApi=employeeApi}:{api?:TrainingApi;employeesApi?:EmployeeApi}){
 const qc=useQueryClient();const records=useQuery({queryKey:['training-records'],queryFn:api.listForHr});const employees=useQuery({queryKey:['employees','training'],queryFn:employeesApi.list});const [open,setOpen]=useState(false);const [form,setForm]=useState<TrainingRecordInput>(empty);const [files,setFiles]=useState<File[]>([]);const [search,setSearch]=useState('');const [editing,setEditing]=useState<TrainingRecord|null>(null);const [documentsFor,setDocumentsFor]=useState<TrainingRecord|null>(null)
 const save=useMutation({mutationFn:async()=>{if(editing){await api.update(editing.id,{...form,employeeIds:[editing.employeeId]});if(files.length)await api.uploadDocuments(editing.id,files)}else{const ids=await api.save(form);if(files.length)for(const id of ids)await api.uploadDocuments(id,files)}},onSuccess:async()=>{setOpen(false);setEditing(null);setForm(empty());setFiles([]);await qc.invalidateQueries({queryKey:['training-records']})}})
 const rows=useMemo(()=>{const q=search.toLowerCase();return (records.data??[]).filter(r=>`${r.employeeName} ${r.topic} ${r.provider??''}`.toLowerCase().includes(q))},[records.data,search]);const hours=(records.data??[]).reduce((n,r)=>n+(r.durationHours??0),0);const spend=(records.data??[]).reduce((n,r)=>n+(r.costUgx??0),0);const horizon=new Date();horizon.setDate(horizon.getDate()+60);const expiring=(records.data??[]).filter(r=>r.expiryDate&&new Date(r.expiryDate)<=horizon).length
 const edit=(r:TrainingRecord)=>{setEditing(r);setForm({employeeIds:[r.employeeId],topic:r.topic,provider:r.provider??'',completionDate:r.completionDate,durationHours:r.durationHours,cost:r.costUgx,status:r.status,expiryDate:r.expiryDate,certificateReference:r.certificateReference??''});setOpen(true)}
 const closeForm=()=>{setOpen(false);setEditing(null);setForm(empty());setFiles([])}
 return <section className="oh-workspace-page"><header className="oh-page-header"><div><p>Learning and compliance</p><h1>Training &amp; Certifications</h1><span>Track employee upskilling, evidence, completion and certificate expiry.</span></div><Button onClick={()=>{closeForm();setOpen(true)}}><Plus size={16}/>Log training</Button></header>
 <div className="oh-stats-grid"><article className="oh-stat-card"><BookOpen/><span>Total records</span><strong>{records.data?.length??0}</strong></article><article className="oh-stat-card"><Clock/><span>Hours logged</span><strong>{hours}</strong></article><article className="oh-stat-card"><span>Total spend</span><strong>UGX {spend.toLocaleString()}</strong></article><article className="oh-stat-card"><AlertTriangle/><span>Expired / expiring</span><strong>{expiring}</strong></article></div>
 <section className="oh-card"><div className="oh-section-header"><div><h2>Training history</h2><p>Legacy-compatible records with secure certificate evidence.</p></div><label className="oh-search-field"><Search size={16}/><input aria-label="Search training" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search employee, topic or provider"/></label></div>{records.isError?<FormError>Training records could not be loaded.</FormError>:null}<div className="oh-table-wrap"><table className="oh-table"><thead><tr><th>Employee</th><th>Topic / provider</th><th>Completed</th><th>Hours</th><th>Cost</th><th>Status</th><th>Certificate</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.employeeName}</strong><small>{r.employeeNumber}</small></td><td>{r.topic}<small>{r.provider??'—'}</small></td><td>{r.completionDate}{r.expiryDate?<small>Expires {r.expiryDate}</small>:null}</td><td>{r.durationHours??'—'}</td><td>{r.costUgx?`UGX ${r.costUgx.toLocaleString()}`:'—'}</td><td>{r.status}</td><td>{r.certificateReference??'—'}<small>{r.certificateCount} file(s)</small></td><td><div className="oh-form-actions"><Button variant="secondary" className="oh-button--small" onClick={()=>edit(r)}>Edit</Button>{r.certificateCount?<Button variant="ghost" className="oh-button--small" onClick={()=>setDocumentsFor(r)}>Files</Button>:null}</div></td></tr>)}</tbody></table></div></section>
 <Modal open={open} title={editing?'Edit training record':'Log training'} onClose={closeForm}><form className="oh-form" onSubmit={e=>{e.preventDefault();save.mutate()}}><div className="oh-form-grid"><label className="oh-field"><span className="oh-field__label">Topic / course *</span><input className="oh-input" value={form.topic} onChange={e=>setForm({...form,topic:e.target.value})}/></label><label className="oh-field"><span className="oh-field__label">Provider</span><input className="oh-input" value={form.provider} onChange={e=>setForm({...form,provider:e.target.value})}/></label><label className="oh-field"><span className="oh-field__label">Completion date *</span><input type="date" className="oh-input" value={form.completionDate} onChange={e=>setForm({...form,completionDate:e.target.value})}/></label><label className="oh-field"><span className="oh-field__label">Duration (hours)</span><input type="number" step="0.5" className="oh-input" value={form.durationHours??''} onChange={e=>setForm({...form,durationHours:e.target.value?Number(e.target.value):null})}/></label><label className="oh-field"><span className="oh-field__label">Cost per employee (UGX)</span><input type="number" className="oh-input" value={form.cost??''} onChange={e=>setForm({...form,cost:e.target.value?Number(e.target.value):null})}/></label><label className="oh-field"><span className="oh-field__label">Status</span><select className="oh-input" value={form.status} onChange={e=>setForm({...form,status:e.target.value as TrainingRecordInput['status']})}><option value="passed">Passed</option><option value="failed">Failed</option><option value="attended">Attended only</option><option value="scheduled">Scheduled</option></select></label><label className="oh-field"><span className="oh-field__label">Expiry date</span><input type="date" className="oh-input" value={form.expiryDate??''} onChange={e=>setForm({...form,expiryDate:e.target.value||null})}/></label><label className="oh-field"><span className="oh-field__label">Certificate ID / reference</span><input className="oh-input" value={form.certificateReference} onChange={e=>setForm({...form,certificateReference:e.target.value})}/></label></div>
 {!editing?<fieldset className="oh-card"><legend>Select employees ({form.employeeIds.length}) *</legend><div className="oh-form-actions"><Button type="button" variant="ghost" onClick={()=>setForm({...form,employeeIds:(employees.data??[]).filter(e=>e.active).map(e=>e.id)})}>All</Button><Button type="button" variant="ghost" onClick={()=>setForm({...form,employeeIds:[]})}>None</Button></div>{(employees.data??[]).filter(e=>e.active).map(emp=><label className="oh-checkbox" key={emp.id}><input type="checkbox" checked={form.employeeIds.includes(emp.id)} onChange={()=>setForm({...form,employeeIds:form.employeeIds.includes(emp.id)?form.employeeIds.filter(id=>id!==emp.id):[...form.employeeIds,emp.id]})}/>{emp.legalName} <small>{emp.departmentName??''}</small></label>)}</fieldset>:null}
 <label className="oh-field"><span className="oh-field__label">Certificate evidence</span><input className="oh-input" type="file" multiple accept="application/pdf,image/jpeg,image/png,image/webp,image/heic,image/heif,image/avif,.heic,.heif" onChange={e=>setFiles(Array.from(e.target.files??[]).slice(0,10))}/><span className="oh-field__hint">Up to 10 PDFs or phone-camera photos, 10 MB each.</span></label>{save.isError?<FormError>{save.error.message}</FormError>:null}<div className="oh-form-actions"><Button type="button" variant="secondary" onClick={closeForm}>Cancel</Button><Button loading={save.isPending} disabled={form.topic.trim().length<2||form.employeeIds.length===0}>Save training record{form.employeeIds.length>1?'s':''}</Button></div></form></Modal><TrainingDocumentsModal api={api} recordId={documentsFor?.id??null} title={documentsFor?.topic??''} canManage onClose={()=>setDocumentsFor(null)}/></section>
}
